version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ./core
    command: uvicorn core.asgi:application --port 8000 --workers 4 --log-level debug --reload
    volumes:
      - ./core:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - ./env_vars_django.txt
    # depends_on:
    #   - redis
  
  rabbitmq:
    image: rabbitmq:management
    restart:  always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379 # Expose Redis port to the host machine

  flower:
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  

      
